### ISSUE TITLE
can't open /dev/mem

### ISSUE THREAD

**Issue by peepo** [fpga-logi/logi-tools#2]
$ logi_loader logipi_top.bit
Loader was compiled for PIB/B+/A/A+ 
can't open /dev/mem 

JP,
recently I've tried to install logi_loader in quite a number of builds on RPi1 in every case this is the result.

in particular I am trying to run with a usb display that requires a particular kernel for framebuffer support: http://www.robopeak.com/blog/?p=406
using this 3.12.28+ build:
http://www.4shared.com/file/7Om2Mo_Bba/sdimage_8g_raspberry-pi_wheezy.html

during logi_loader build the only error was:
Enable SPI
sed: -e expression #1, char 11: unterminated `s' command

**Comment by peepo** [comment]
maybe sudo issue checking...

**Comment by jpiat** [comment]
You are right the script must be run as sudo. This is an issue as the script only run some commands prefixed with sudo when all should be run as sudo. I'll try to fix this asap.
